// Server

import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className="flex w-screen h-screen items-center px-3 justify-center bg-[#0e0e10]">
          {children}
        </body>
      </Provider>
    </html>
  );
}
